# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PPC_KO <- function(X, id_CV, threshold_k, alpha, n_disc) {
    .Call('_PPCKO_PPC_KO', PACKAGE = 'PPCKO', X, id_CV, threshold_k, alpha, n_disc)
}

