# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PPC_KO <- function(X, id_CV, id_p_for_k, threshold_k, alpha = 0.75, n_disc = 21L, k = 0L, alpha_min = 0.00000000001, alpha_max = 10, id_p_imposed = "No", id_rem_nan = NULL) {
    .Call('_PPCKO_PPC_KO', PACKAGE = 'PPCKO', X, id_CV, id_p_for_k, threshold_k, alpha, n_disc, k, alpha_min, alpha_max, id_p_imposed, id_rem_nan)
}

read_data_na <- function(X) {
    .Call('_PPCKO_read_data_na', PACKAGE = 'PPCKO', X)
}

