# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PPC_KO <- function(X, id_CV = "NoCV", threshold_ppc = 0.95, alpha = 0.75, k = 0L, id_rem_nan = NULL) {
    .Call('_PPCKO_PPC_KO', PACKAGE = 'PPCKO', X, id_CV, threshold_ppc, alpha, k, id_rem_nan)
}

read_data_na <- function(X) {
    .Call('_PPCKO_read_data_na', PACKAGE = 'PPCKO', X)
}

test_lr <- function(X, Y) {
    .Call('_PPCKO_test_lr', PACKAGE = 'PPCKO', X, Y)
}

test_adf <- function(X, lag_order) {
    .Call('_PPCKO_test_adf', PACKAGE = 'PPCKO', X, lag_order)
}

