# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PPC_KO <- function(X, id_CV = "NoCV", alpha = 0.75, k = 0L, threshold_ppc = 0.95, alpha_vec = NULL, k_vec = NULL, toll = 1e-4, disc_ev = NULL, left_extreme = 0, right_extreme = 1, min_size_ts = NULL, max_size_ts = NULL, err_ret = 0L, num_threads = NULL, id_rem_nan = NULL) {
    .Call('_PPCKO_PPC_KO', PACKAGE = 'PPCKO', X, id_CV, alpha, k, threshold_ppc, alpha_vec, k_vec, toll, disc_ev, left_extreme, right_extreme, min_size_ts, max_size_ts, err_ret, num_threads, id_rem_nan)
}

PPC_KO_2d <- function(X, id_CV = "NoCV", alpha = 0.75, k = 0L, threshold_ppc = 0.95, alpha_vec = NULL, k_vec = NULL, toll = 1e-4, disc_ev_x1 = NULL, num_disc_ev_x1 = 10L, disc_ev_x2 = NULL, num_disc_ev_x2 = 10L, left_extreme_x1 = 0, right_extreme_x1 = 1, left_extreme_x2 = 0, right_extreme_x2 = 1, min_size_ts = NULL, max_size_ts = NULL, err_ret = 0L, num_threads = NULL, id_rem_nan = NULL) {
    .Call('_PPCKO_PPC_KO_2d', PACKAGE = 'PPCKO', X, id_CV, alpha, k, threshold_ppc, alpha_vec, k_vec, toll, disc_ev_x1, num_disc_ev_x1, disc_ev_x2, num_disc_ev_x2, left_extreme_x1, right_extreme_x1, left_extreme_x2, right_extreme_x2, min_size_ts, max_size_ts, err_ret, num_threads, id_rem_nan)
}

KO_check_hps <- function(X) {
    .Call('_PPCKO_KO_check_hps', PACKAGE = 'PPCKO', X)
}

KO_check_hps_2d <- function(X, dim_x1, dim_x2) {
    .Call('_PPCKO_KO_check_hps_2d', PACKAGE = 'PPCKO', X, dim_x1, dim_x2)
}

data_2d_wrapper_from_list <- function(Xt) {
    .Call('_PPCKO_data_2d_wrapper_from_list', PACKAGE = 'PPCKO', Xt)
}

